// Initialize Firebase

// fill the config with the info generated by firebase
var firebaseConfig = {
  apiKey: "AIzaSyA9RpJf7Ukpx7Qjs-uFhhtke4BObprh648",
  authDomain: "thisisatestfordrawing.firebaseapp.com",
  databaseURL: "https://thisisatestfordrawing.firebaseio.com",
  projectId: "thisisatestfordrawing",
  storageBucket: "thisisatestfordrawing.appspot.com",
  messagingSenderId: "1096662812271",
  appId: "1:1096662812271:web:a7b39effae9fe6d38def9a"
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);
