// Initialize Firebase

// fill the config with the info generated by firebase
var config = {
  apiKey: "YOUR KEY",
  authDomain: "",
  databaseURL: "m",
  projectId: "",
  storageBucket: "",
  messagingSenderId: ""
};
firebase.initializeApp(config);
