// Initialize Firebase

// fill the config with the info generated by firebase
var config = {
  apiKey: "AIzaSyD0KOVnqvMcFnQiat1KLqU0r7Vo5J8m828",
  authDomain: "pics-json.firebaseapp.com",
  databaseURL: "https://pics-json.firebaseio.com",
  projectId: "pics-json",
  storageBucket: "pics-json.appspot.com",
  messagingSenderId: "900146591874"
};
firebase.initializeApp(config);
